### ISSUE TITLE
opendj docker run fails : cp: target ‘instances/instance1’ is not a directory

### ISSUE THREAD

**Issue by jogre** [ForgeRock/docker#3]
Hi Warren,

I'm getting an error deploying the docker (see below). I think you need, in the run.sh to make the directory before executing the cp command. Something like:

 mkdir instances/instance1/
 cp -pr instances/template/* instances/instance1/

Here's the docker run. See error towards the end :

Joachims-MacBook-Pro:10_docker joachim$ docker run --name zorro-aws-c3 -h ldap.zorrosmash.com -p 389:389 wstrange/opendj-nightly
Unable to find image 'wstrange/opendj-nightly:latest' locally
latest: Pulling from wstrange/opendj-nightly
9ee13ca3b908: Pull complete 
23cb15b0fcec: Pull complete 
5e5f21412e19: Pull complete 
df82ac64861d: Pull complete 
ce5064412ef8: Pull complete 
46cb1e153bac: Pull complete 
65e700d53fe2: Pull complete 
e4c1902ba8e2: Pull complete 
041291567735: Pull complete 
38bbdcdf22d3: Pull complete 
ee4c5fbd36c4: Pull complete 
d4849089125b: Pull complete 
7437250649ef: Pull complete 
d33db951ae28: Pull complete 
3e56b2d0f8a9: Pull complete 
0b6a8fc26e04: Pull complete 
06a6693e22af: Pull complete 
04de491ce43c: Pull complete 
69a2cb358ef1: Pull complete 
8a1daa62827a: Pull complete 
Digest: sha256:bf36d7adfb22064205dffa1a58ebf1b56a52b0923fdde0d97e35c2cb66e9ef2f
Status: Downloaded newer image for wstrange/opendj-nightly:latest
Instance Directory is empty. Creating new instance from template
cp: target ‘instances/instance1’ is not a directory
The Directory Server could not acquire an exclusive lock on file /opt/opendj/./instances/instance1/locks/server.lock: The attempt to obtain an exclusive lock on file /opt/opendj/./instances/instance1/locks/server.lock was rejected because the attempt to create the lock file failed: IOException(No such file or directory). This generally means that another instance of this server is already running
Joachims-MacBook-Pro:10_docker joachim$ pwd

**Comment by wstrange** [comment]
Hi Joachim

I just pushed a fix for this but have not tested it yet.  Let me know if it works

**Comment by jogre** [comment]
Thanks. Works !
