### ISSUE TITLE
OpenIG Docker file

### ISSUE THREAD

**Issue by miguelfgar** [ForgeRock/docker#4]
Hi,

I'm using the OpenAM Docker file already. However I would like to use OpenIG in combination with OpenAM.

Is there any OpenIG Docker file that could be used to build the Docker image? I was not able to find it in this repository nor in Docker Hub.

Thanks

**Comment by wstrange** [comment]
Hi Miguel 


I will see if I can get an example up by the end of the week, 

We will be moving this to our stash repo:

https://stash.forgerock.org/projects/DOCKER/repos/docker/browse

You will need  a community stash account to pull the repo

**Comment by wstrange** [comment]
Miguel

Mark just added an IG example

**Comment by miguelfgar** [comment]
Hi @wstrange,

thanks so much for your quick response.

I have created a 'backstage' account as explained here: https://forgerock.org/projects/getting-the-source-code/  and now I'm able to access the stash repo you mentioned.
However, I can only see a few public repos (I can't see the openam, openig, opendj.. source code -even though they are also published in Github - as explained in the ULR above).
Is this what you would expect and what I should expect? Just to be sure.
Maybe as you are moving code the content published for community users does not match what is explained here: https://forgerock.org/projects/getting-the-source-code/

Anyway, thanks so much. Now I'm registered and when you move the projects there I will be able to access.

The docker file came in very handy :-)
